### ISSUE TITLE
Add alumni/expats page

### ISSUE THREAD

**Issue by ethanwhite** [weecology/website#8]
Old page: https://web.archive.org/web/20170320143447/http://weecology.org:80/expats

**Comment by henrykironde** [comment]
Trying to collect information from the alumi. Should we create a separate folder for the Alumni, or the template will take care of showing that.

- [ ] Elita Baldridge
- [ ] Sarah (Mohlman) Supp
- [ ] Katherine Thibault
- [ ] Ben Morris (Waiting to accept connection, no message sent as yet)
- [ ] Akash Goel (Sent message)
- [ ] Mikaelle Giffen
- [ ] Clayton Bingham
- [ ] Xiao Xiao (Sent Xiao Xiao a linkedin message)
- [ ] Kari Norman
- [ ] Ken Locey
- [ ] Dan McGlinn
